version: "3.9"
services:
  painting-postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "painting2"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/postgres:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
  painting-redis:
    image: redis:6
    volumes:
      - ./db/redis:/data
